In [104]:
my_dictionary = {
    "name":"pratik",
    "lastname":"kolhe",
    "class":"cse sy3",
    "prn":22404319
}

print("my dictionary is " + str(my_dictionary))
print()
print("from my dictionary prn is " + str(my_dictionary["prn"]))
print()
print("type of my_dictionary " + str(type(my_dictionary)))
print()

random_name = dict()
random_name_keys = [1, 2, 3, 4, 5]
random_name_values = ["pratik", "sakshi", "pranav", "unnati", "atharva"]
random_name = dict(zip(random_name_keys, random_name_values))
print("created random_name using fromkeys function of dict class " + str(random_name))

some = dict(
    {"name":"pratik"}
)
print()
print(some["name"])


my dictionary is {'name': 'pratik', 'lastname': 'kolhe', 'class': 'cse sy3', 'prn': 22404319}

from my dictionary prn is 22404319

type of my_dictionary <class 'dict'>

created random_name using fromkeys function of dict class {1: 'pratik', 2: 'sakshi', 3: 'pranav', 4: 'unnati', 5: 'atharva'}

pratik


In [100]:
students = {
    '101': 'Alice',
    '102': 'Bob',
    '103': 'Charlie'
}

subjects = ['Math', 'Physics', 'Chemistry']

greeting = 'Hello, ' + students['101'] + '!'

print('Dictionary:', students)
print('List:', subjects)
print('String:', greeting)

students['104'] = 'David'
print('Updated Dictionary:', students)

subjects.append('Biology')
print('Updated List:', subjects)

welcome_message = greeting.upper()
print('Uppercase String:', welcome_message)


Dictionary: {'101': 'Alice', '102': 'Bob', '103': 'Charlie'}
List: ['Math', 'Physics', 'Chemistry']
String: Hello, Alice!
Updated Dictionary: {'101': 'Alice', '102': 'Bob', '103': 'Charlie', '104': 'David'}
Updated List: ['Math', 'Physics', 'Chemistry', 'Biology']
Uppercase String: HELLO, ALICE!


In [101]:
l = [1, 2, 3]
al = [5, 6, 7]
bl = []
bl.append(l)
bl.append(al)
print(bl)
print()
print("type of l " + str(type(l)))
print("type of al " + str(type(al)))
print("type of bl " + str(type(bl)))
print()
cl = [l, al]
print(cl)
print()
print(cl[0][1])


[[1, 2, 3], [5, 6, 7]]

type of l <class 'list'>
type of al <class 'list'>
type of bl <class 'list'>

[[1, 2, 3], [5, 6, 7]]

2


In [1]:
my_str = "pratik"
size = 0
my_name = dict()
print("my string is " + my_str)
print()
for a in my_str:
    size += 1
    my_name[size] = a

print("size of my_str pratik is " + str(size))
print(my_name)

my string is pratik

size of my_str pratik is 6
{1: 'p', 2: 'r', 3: 'a', 4: 't', 5: 'i', 6: 'k'}


In [2]:
letter = 'a'
occurrence = my_str.count(letter)

my_name[size + 1] = occurrence

print("Updated dictionary:", my_name)
print("Type of my_name:", type(my_name))

Updated dictionary: {1: 'p', 2: 'r', 3: 'a', 4: 't', 5: 'i', 6: 'k', 7: 1}
Type of my_name: <class 'dict'>


In [4]:
birthday = "18/12/2005"
print("Your Birthday: " + birthday)
day, month, year = birthday.split('/')
print("Day:" + day)
print("Month:"+month)
print("Year:"+year)

birthday_dict = {
    "day":day,
    "month":month,
    "year":year
}

print("Separated Dictionary: " + str(birthday_dict))
print("Joining Now Dictionary: " + " ".join(birthday_dict.values()))

months = {
    "01": "January",
    "02": "February",
    "03": "March",
    "04": "April",
    "05": "May",
    "06": "June",
    "07": "July",
    "08": "August",
    "09": "September",
    "10": "October",
    "11": "November",
    "12": "December"
}

print(str(birthday_dict["day"]) + " " + months[birthday_dict["month"]] + " " + birthday_dict["year"])
print(f'{birthday_dict["day"]} { months[birthday_dict["month"]] } {birthday_dict["year"]}')


Your Birthday: 18/12/2005
Day:18
Month:12
Year:2005
Separated Dictionary: {'day': '18', 'month': '12', 'year': '2005'}
Joining Now Dictionary: 18 12 2005
18 December 2005
18 December 2005


In [ ]:
# Input matrices
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[4, 5], [6, 7]]

print("Printing elements of first matrix")
for row in matrix1:
	for element in row:
		print(element, end=" ")
	print()

print("Printing elements of second matrix")
for row in matrix2:
	for element in row:
		print(element, end=" ")
	print()

# Subtracting two matrices
result = [[0, 0], [0, 0]]
for i in range(len(matrix1)):
	for j in range(len(matrix1[0])):
		result[i][j] = matrix1[i][j] - matrix2[i][j]

# Printing the result
print("Subtraction of two matrix")
for row in result:
	for element in row:
		print(element, end=" ")
	print()

# Addition two matrices
result = [[0, 0], [0, 0]]
for i in range(len(matrix1)):
	for j in range(len(matrix1[0])):
		result[i][j] = matrix1[i][j] + matrix2[i][j]

# Addition the result
print("Subtraction of two matrix")
for row in result:
	for element in row:
		print(element, end=" ")
	print()


In [5]:
# %pip install numpy
import numpy as np

m = [[4, 5, 4], [6, 4, 4]]
n = [[5, 5, 5], [5, 5, 5]]
multi = np.dot(m,n)
print("Addition of matrix is \n" + str(np.add(m, n)))
print("\n\nSubstraction of matrix is \n"+str(np.subtract(m, n)))
print("\n\nMultiplication of matrix is \n", multi)
print("\nTranspose of matrix is \n"+str(np.transpose(m)))

Addition of matrix is 
[[ 9 10  9]
 [11  9  9]]


Substraction of matrix is 
[[-1  0 -1]
 [ 1 -1 -1]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [13]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 1, 1, 2, 2, 2, 2, 3,]

print("taken list is ", l)

# mean program here
mean_numpy = np.mean(l)
mean_manual = sum(l) / len(l)
mean_loop = 0
for a in l:
    mean_loop += a
mean_loop = mean_loop / len(l)

print("mean using numpy is " + str(mean_numpy))
print("mean using manual is " + str(mean_manual))
print("mean using loop is " + str(mean_loop))

# median program here
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 1, 1, 2, 2, 2, 2, 3,]
l.sort()
if len(l) % 2 == 0:
    median = (l[len(l) // 2] + l[len(l) // 2 - 1]) / 2
else:
    median = l[len(l) // 2]
median_numpy = np.median(l)
print("median using numpy is " + str(median_numpy))
print("median using manual is " + str(median))

# mode program here
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 1, 1, 2, 2, 2, 2, 3,]
most_common = 0
print()
print()
print("Bincount Function of numpy "+str(np.bincount(l)))
print("mode using numpy is " + str(np.argmax(np.bincount(l))))
for a in l:
    if l.count(a) > most_common:
        most_common = a
print("mode using manual is " + str(most_common))


taken list is  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 1, 1, 2, 2, 2, 2, 3]
mean using numpy is 3.8333333333333335
mean using manual is 3.8333333333333335
mean using loop is 3.8333333333333335
median using numpy is 2.5
median using manual is 2.5


Bincount Function of numpy [0 4 5 2 1 1 1 1 1 1 1]
mode using numpy is 2
mode using manual is 2


In [14]:
import statistics as st

l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 1, 1, 2, 2, 2, 2, 3]
print("mean using statistics is " + str(st.mean(l)))
print("median using statistics is " + str(st.median(l)))
print("mode using statistics is " + str(st.mode(l)))

mean using statistics is 3.8333333333333335
median using statistics is 2.5
mode using statistics is 2


In [5]:
# creating custom functions for mean, median and mode
def my_mean(l):
    mean_loop = 0
    for a in l:
        mean_loop += a
    mean_loop = mean_loop / len(l)
    return mean_loop

def my_median(l):
    l.sort()
    if len(l) % 2 == 0:
        median = (l[len(l) // 2] + l[len(l) // 2 - 1]) / 2
    else:
        median = l[len(l) // 2]
    return median

def my_mode(l):
    most_common = 0
    for a in l:
        if l.count(a) > most_common:
            most_common = a
    return most_common

#calling my functions
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 1, 1, 2, 2, 2, 2, 3]
mean_using_myfunction = my_mean(l)
median_using_myfunction = my_median(l)
mode_using_myfunction = my_mode(l)
print("mean using my function is " + str(mean_using_myfunction))
print("median using my function is " + str(median_using_myfunction))
print("mode using my function is " + str(mode_using_myfunction))

mean using my function is 3.8333333333333335
median using my function is 2.5
mode using my function is 2


In [2]:
#current date and time
import datetime

now = datetime.datetime.now()
print("Current date and time is " + now.strftime("%Y-%m-%d %H:%M:%S"))
print("Current year is " + now.strftime("%Y"))
print("Current month is " + now.strftime("%m"))
print("Current day is " + now.strftime("%d"))
print("Current hour is " + now.strftime("%H"))
print("Current minute is " + now.strftime("%M"))
print("Current second is " + now.strftime("%S"))

Current date and time is 2025-01-19 18:07:21
Current year is 2025
Current month is 01
Current day is 19
Current hour is 18
Current minute is 07
Current second is 21


In [2]:
#demonstrating the use of OOPs concepts
class Student:
    def __init__(self, name, age, roll_number):
        self.name = name
        self.age = age
        self.roll_number = roll_number

    def display(self):
        print("Name: " + self.name)
        print("Age: " + str(self.age))
        print("Roll Number: " + str(self.roll_number))

    def update(self, name, age=None, roll_number=None):
        self.name = name
        if age is not None:
            self.age = age
        if roll_number is not None:
            self.roll_number = roll_number

student1 = Student("Pratik", 20, 22404319)
student1.display()
student1.update("Sakshi")
student1.display()

Name: Pratik
Age: 20
Roll Number: 22404319
Name: Sakshi
Age: 20
Roll Number: 22404319


In [2]:
A = [[1,2],[4,5]] 
B = [[7,8],[9,10]] 
rows = len(A) 
cols = len(A[0]) 

# Element wise addition 
# C = [[0 for i in range(cols)] for j in range(rows)] 
C = [[0 for i in range(cols)]] 
print(C)

[[0, 0]]
